FROM golang:1.17.5-alpine3.14
WORKDIR /app
COPY . .
RUN apk add --no-cache make
RUN apk add --no-cache --update postgresql-client
RUN apk add --no-cache git
RUN CGO_ENABLED=0 go get -u github.com/pressly/goose/v3/cmd/goose
CMD goose -dir migrations up